-- ///////to use file, put it in resourse directory
--INSERT INTO book (name)
--VALUES ("asdasdas");
--INSERT INTO book (name)
--VALUES ("java");
--INSERT INTO book (name)
--VALUES ("c#");
--INSERT INTO book (name)
--VALUES ("python");
