--INSERT INTO springData.book (name)
--VALUES ("asdasdas");
--INSERT INTO springData.book (name)
--VALUES ("java");
--INSERT INTO springData.book (name)
--VALUES ("c#");
--INSERT INTO springData.book (name)
--VALUES ("python");
